env:
  browser: true
  commonjs: true
  es2021: true
extends:
  - airbnb-base
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 13
settings:
  import/resolver: {
      node: {
        extensions: [".js", ".jsx", ".ts", ".tsx"]
      }
    }
plugins:
  - '@typescript-eslint'
  - 'jest'
rules:
  import/extensions: 0
  no-console: 0
  import/prefer-default-export: 0
